### PR TITLE
added color support for windows terminal

### LINKED ISSUE #8: Test application compatibility with Windows 10
The following must be tested to complete the following QA check
- [ ] Testing command-line arguments in Command Prompt
- [ ] Testing command-line arguments in Powershell

### LINKED ISSUE #11: Colors not showing up in Windows 10
The command line doesn't show the colors in windows 10 as it does in linux. Reason is that colors used are ANSI escape codes and windows won't support it.  

Current output in windows:

Screenshot from 2020-10-15 18-27-58

### PR DESCRIPTION
**Pull request by KrishKayc**
- Set the flag ENABLE_VIRTUAL_TERMINAL_PROCESSING for windows alone.
- Added go.mod file 
Screenshot from 2020-10-16 15-46-28
Screenshot from 2020-10-16 15-48-08

### CODE REVIEW

**Comment by gridhead** [comment]
@tripathyprateek Could you please review this for me? Thanks in advance.

**Comment by gridhead** [comment]
@s0umadeep Could you please review this for me? Thanks in advance.

**Comment by gridhead** [comment]
Also before @s0umadeep actually gets into reviewing, @KrishKayc please do make sure that you rebase your fork's branch to the latest commits made to the original repo's main.

**Comment by KrishKayc** [comment]
@t0xic0der Resolved all the conflicts with the base branch's main. Also, have added a package which handles the windows flag assignment instead of duplicating the code in our code base. Please do check that, it is a one liner now.

**Comment by tripathyprateek** [comment]
Looks good to me. Great job @KrishKayc . @t0xic0der take some time out and update README on how to build this project.

**Comment by gridhead** [comment]
> @t0xic0der take some time out and update README on how to build this project.

Sure thing.

**Pull request merged**
